apiVersion: batch/v1
kind: Job
metadata:
  name: processador-diagramas-processingservice-migrations
  namespace: homolog
  labels:
    app: processador-diagramas-processingservice
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: processador-diagramas-processingservice
        job-name: processador-diagramas-processingservice-migrations
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: 767398027345.dkr.ecr.us-east-1.amazonaws.com/processador-diagramas-processingservice:${IMAGE_TAG}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: processador-diagramas-processingservice-secrets
          command:
            - /bin/sh
            - -c
            - /app/efbundle --connection "$ConnectionStrings__DefaultConnection"