namespace ProcessadorDiagramas.ProcessingService.Application.Queries.GetDiagramProcessingJobByAnalysisProcessId;

public sealed record GetDiagramProcessingJobByAnalysisProcessIdQuery(Guid DiagramAnalysisProcessId);
